version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - checkout
      - run: sudo pip install awscli
      - run: sudo tar --exclude='.*' -czvf /tmp/$CIRCLE_PROJECT_REPONAME.tar.gz ~/project/
      - store_artifacts:
          path: /tmp/$CIRCLE_PROJECT_REPONAME.tar.gz
          destination: $CIRCLE_PROJECT_REPONAME.tar.gz
      
   deploy:
    steps:
      - run: aws s3 cp /tmp/$CIRCLE_PROJECT_REPONAME.tar.gz s3://test-s3awscd/binaries/

workflows:
  version: 2
  workflow:
    jobs:
      - build
      - deploy
          type: approval
          requires:
            - build
